### ISSUE TITLE
Is it possible to share depenedencies / `caches/modules-2` between multiple jobs?

### ISSUE THREAD

**Issue by scana** [gradle/gradle-build-action#1033]
Hi! Thank you for this GitHub Action, it's been a blast using it so far 😄

I am currently running a single workflow with 4 separate jobs structured this way:

```
ktLint -> 
       unit-tests
       android-lint
       screenshot-test
```

it seems that each of those jobs would publish it's own dependencies cache (and instrumentation jars):
<img width="300" alt="Screenshot 2024-01-11 at 12 26 06" src="https://github.com/gradle/gradle-build-action/assets/1139325/f98bfba3-edd2-493e-a4e0-54c2325cfea9">

Is there a way to let only one of those jobs publish those, while the rest would be able to reuse them?
I tried the following:

```yml
  ktlint:
    name: KtLint
      ...
      - name: Run ktlint
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          gradle-home-cache-excludes: |
            caches/jars-9
            caches/modules-2
          arguments: ktlintCheck

  unit-tests:
    name: Unit Tests
      ...
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: test
```
but then it seems like those cache entries are omitted / not downloaded at all:
```
Entry: Gradle User Home
    Requested Key : v8-gradle|Linux|checks-ktlint[37a6259cc0c1dae299a7866489dff0bd]-e17cbd2bab4030bc45ad8460cf3d2318bd6bc322
    Restored  Key : v8-gradle|Linux|checks-ktlint[37a6259cc0c1dae299a7866489dff0bd]-6ceb06cc32243f25912bd344b7d0c2b9a1455409
              Size: 293 MB (307078181 B)
              (Entry restored: partial match found)
    Saved     Key : v8-gradle|Linux|checks-ktlint[37a6259cc0c1dae299a7866489dff0bd]-e17cbd2bab4030bc45ad8460cf3d2318bd6bc322
              Size: 293 MB (307121161 B)
              (Entry saved)
---
Entry: /home/runner/.gradle/caches/8.4/generated-gradle-jars/gradle-api-8.4.jar
    Requested Key : generated-gradle-jars-1a83665c481822ee3817bdf1f75747ae
    Restored  Key : generated-gradle-jars-1a83665c481822ee3817bdf1f75747ae
              Size: 35 MB (36850579 B)
              (Entry restored: exact match found)
    Saved     Key : 
              Size: 
              (Entry not saved: contents unchanged)
---
Entry: /home/runner/.gradle/wrapper/dists/gradle-8.4-bin/1w5dpkrfk8irigvoxmyhowfim
    Requested Key : wrapper-zips-f82d94dd741812d9afc7aad8d4ab116c
    Restored  Key : wrapper-zips-f82d94dd741812d9afc7aad8d4ab116c
              Size: 124 MB (130236794 B)
              (Entry restored: exact match found)
    Saved     Key : 
              Size: 
              (Entry not saved: contents unchanged)
```
