### ISSUE TITLE
working-directory not honoured

### ISSUE THREAD

**Issue by davidmoten** [gradle/gradle-build-action#1062]
My team had to stop using gradle-build-action because `working-directory` not honoured. We've stopped using it because of this issue but I thought I'd let you know. cc @TristanSpeakEasy

```
jobs:
  java-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
     ...
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
          cache: "gradle"
```
