### ISSUE TITLE
Move post-action into main-action to allow 3rd party GitHub action runner

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-build-action#146]
GitHub action runner unfortunately only supports the three major OS systems, e.g. Windows, macOS, Linux (unlike GitLab runner). Native users may want to run their Gradle build on other self-hosted systems such as FreeBSD, Solaris, etc. or other architectures like PPC, MIPS, ARM, etc. The [`github-act-runner`](https://github.com/ChristopherHX/github-act-runner) seems to be the recommended solution. Unfortunately, [this runner doesn't support pre/post actions](https://github.com/ChristopherHX/github-act-runner#known-limitations). Double unfortunately, [GitHub doesn't seem to be interested in solving support for more OS/Architecture any time soon](https://github.com/actions/virtual-environments/issues/2529#issuecomment-766833650).

It seems to be quite trivial to modify the action and [execute the only cache.save()](https://github.com/gradle/gradle-build-action/blob/main/src/post.ts#L14) in the main-action allowing wider support for this GitHub action.

**Comment by bigdaz** [comment]
We certainly cannot do this by default, since we only want to cache the Gradle User Home after all Gradle invocations have completed. In fact, we now support (and recommend) that you use this action as a kind of "Setup Gradle" step, and then invoke Gradle directly in subsequent steps.

A potential solution would be to provide a configuration option (or a separate action) that effectively runs the post action alone. Then you would do something like:
```
- name: Setup Gradle
   uses: gradle/gradle-build-action@v2
   with:
      cache-read-only: true
- name: Run Gradle
   run: ./gradlew build
- name: Cache Gradle
   uses: gradle/gradle-build-action@v2
   with:
       cache-save-only: true
```

I'd be willing to entertain a PR to add such a feature, even though it feels like a bit of a hack. However, I think a better option would be to add `post-action` support to `github-act-runner`.
