### ISSUE TITLE
Automatically perform wrapper validation check

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#151]
Currently, we recommend that users configure a separate workflow running the [wrapper-validation-action](https://github.com/marketplace/actions/gradle-wrapper-validation) to verify that the Gradle wrapper jar is not corrupted.

Doing this automatically for any workflow using `gradle-build-action` would increase coverage of wrapper validation and reduce the complexity for users adopting Gradle with GitHub actions.

**Comment by eygraber** [comment]
Is there any timeline on this happening?

**Comment by erichaagdev** [comment]
> Currently, we recommend that users configure a separate workflow running the [wrapper-validation-action](https://github.com/marketplace/actions/gradle-wrapper-validation) to verify that the Gradle wrapper jar is not corrupted.

I would recommend adding the Gradle wrapper validation check immediately after checkout in any workflow that may run a Gradle wrapper. This eliminates the risk of potentially running a bad wrapper at all in any workflow. For example: 

```yaml
name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew clean build
```
