### ISSUE TITLE
Property 'credentials.username' doesn't have a configured value.

### ISSUE THREAD

**Issue by patsevanton** [gradle/gradle-build-action#164]
Hello!
Thanks for Gradle-build-action

I try to publish artifacts to Maven Central by article https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle

config
```
name: Publish package to the Maven Central Repository

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: gpg version
        run: gpg --version
      - name: gpg list-keys
        run: gpg --list-keys
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

```

Error
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':publishKotlinMultiplatformPublicationToMavenRepository' (type 'PublishToMavenRepository').
  - In plugin 'org.gradle.maven-publish' type 'org.gradle.api.publish.maven.tasks.PublishToMavenRepository' property 'credentials.username' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'credentials.username'.
      2. Mark property 'credentials.username' as optional.
 ```

Github action https://github.com/Drill4J/logger-api/blob/master/.github/workflows/publish-to-maven-central.yml

Log in GitHub action https://github.com/Drill4J/logger-api/runs/5155412191?check_suite_focus=true
