### ISSUE TITLE
How to disable cache?

### ISSUE THREAD

**Issue by ThePieMonster** [gradle/gradle-build-action#175]
How would I go about disabling Gradle from using a cache?

```
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make Gradlew Executable
      run: chmod +x ./gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        
```
