### ISSUE TITLE
Add resolved Gradle version to action outputs

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle-build-action#259]
It would be great to have the resolved Gradle version as an output of the action; that way one could use `gradle-version: current` and later pass that version as input to the Gradle build (to be passed to the Gradle TestKit, that requires a specific version).

`actions/setup-java` for instance exposes the `version` and `path` of the provisioned JDK.

For example here, always testing with the current stable version without having to update the workflow every time:
```yaml
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: ["current", "6.8"] # some specific versions, plus the current stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: ${{ matrix.gradle }}
          # Only write to the cache for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Execute Gradle build
        run: ./gradlew functionalTest -Ptest.gradle-version=${{ steps.setup-gradle.outputs.version }}
```
