### ISSUE TITLE
Support for caching the local build cache

### ISSUE THREAD

**Issue by Kami** [gradle/gradle-build-action#32]
Right now this plugin supports caching of configuration, wrapper and dependencies, but not actual caching of pre-built classes and other build artifacts (``~/.gradle/caches/build-cache-1`` directory aka build caching - https://docs.gradle.org/current/userguide/build_cache.html).

Caching actual build artifacts can speed things up substantially when running multiple gradle tasks in parallel as part of separate jobs - this way each of those tasks can re-use the existing build cache.

Right now, I use a "workaround" which looks something like this:

```yaml
...
      - name: Restore Gradle Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/build-cache-1/
          key: v1-deps-gradle-build-cache-${{ hashFiles('**/*.gradle', 'src/**/*.java') }}

      - name: Gradle Dist Tar
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: wrapper
          arguments: --no-daemon --build-cache downloadDependencies distTar -i
          wrapper-cache-enabled: true
          configuration-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle/dependency-locks/**
          dependencies-cache-exact: true
...
```

I think it would be nice to also support this functionality natively in this action since it already supports caching other types of data.

In fact, I hope to get a chance this week and take a stab at implementing this myself.

I do know there are some gotchas and edge cases which I need to handle correctly since just the other day I needed to re-implement all the caching from scratch for Argo project and I was bitten by some of them.
