### ISSUE TITLE
Allow action to save/restore configuration-cache state on runners with persistent Gradle User Home

### ISSUE THREAD

**Issue by milis92** [gradle/gradle-build-action#345]
Action will ignore saving/restoring configuration cache from the projects .gradle directory if it detects that Gradle User home exists on the host.

Logs from the gradle-build-action setup step:
```
Run gradle/gradle-build-action@v2
  with:
    cache-read-only: false
    gradle-version: wrapper
    cache-disabled: false
    cache-write-only: false
    gradle-home-cache-includes: caches
  notifications
  
    generate-job-summary: true
    gradle-home-cache-strict-match: false
    workflow-job-context: null
Gradle User Home already exists: will not restore from cache.
```

Following task execution:
```
Run ./gradlew ktLintCheck
Starting a Gradle Daemon, 1 busy and 1 stopped Daemons could not be reused, use --status for details
Configuration cache is an incubating feature.
Configuration on demand is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: ktLintCheck
```

The desired outcome would be to restore configuration cache independently of restoring GRADLE_HOME state
