### ISSUE TITLE
Unable to locate executable file: /home/runner/work/.../gradlew

### ISSUE THREAD

**Issue by samueleyre** [gradle/gradle-build-action#43]
My configuration has stopped working suddenly ( since december 2020 ). With this error message : 

```
Unable to locate executable file: /home/runner/work/wecolearn/wecolearn/front/android/gradlew. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

This is my config : 

```
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install capacitor plugins
        run : cd front && ./node_modules/@ionic/cli/bin/ionic capacitor update
      - uses: eskatos/gradle-command-action@v1.3.0
        with:
          arguments: :app:bundleRelease
          gradle-executable: front/android/gradlew
          build-root-directory: front/android
          wrapper-directory: front/android/gradle/wrapper
```
