### ISSUE TITLE
Post-action fails when running multiple builds in the same step with configuration-cache enabled

### ISSUE THREAD

**Issue by CharlieTap** [gradle/gradle-build-action#441]
I'm attempting to configure this action in conjunction with using the gradle profiler

I'm running the workflow on the standard github ubuntu-latest runner

My config is the following:

```
  benchmark:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Install and run the gradle profiler
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradleprofiler 0.18.0
          gradle-profiler --benchmark --scenario-file gradle/benchmark.scenarios assembleDebug --gradle-user-home ~/.gradle

```

But I'm getting the following failure in the Post Setup Gradle step:

`Post job cleanup.
In final post-action step, saving state and writing summary
Warning: Unhandled error in Gradle post-action - job will continue: SyntaxError: Unexpected token { in JSON at position 310
SyntaxError: Unexpected token { in JSON at position 310
    at JSON.parse (<anonymous>)
    at /home/runner/work/_actions/gradle/gradle-build-action/v[2](https://github.com/CharlieTap/motdujour/actions/runs/3119036265/jobs/5058738131#step:12:2)/dist/post/index.js:64660:21
    at Array.map (<anonymous>)
    at loadBuildResults (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/post/index.js:64657:44)
    at Object.<anonymous> (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/post/index.js:66201:67)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/gradle/gradle-build-action/v2/dist/post/index.js:6615[3](https://github.com/CharlieTap/motdujour/actions/runs/3119036265/jobs/5058738131#step:12:3):71
    at new Promise (<anonymous>)
    at __webpack_modules__.8652.__awaiter (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/post/index.js:661[4](https://github.com/CharlieTap/motdujour/actions/runs/3119036265/jobs/5058738131#step:12:4)9:12)
    at Object.complete (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/post/index.js:6619[5](https://github.com/CharlieTap/motdujour/actions/runs/3119036265/jobs/5058738131#step:12:5):[12](https://github.com/CharlieTap/motdujour/actions/runs/3119036265/jobs/5058738131#step:12:12))`

**Comment by bigdaz** [comment]
Thanks for the report. The error is happening when attempting to read the build result files, that capture various details about each Gradle invocation. These will be located in `$RUNNER_TEMP/.build-results`.

- Is this a repeatable failure? 
- If so, can you please capture the `$RUNNER_TEMP/.build-results` directory in a final step in your workflow?

You can use the core [upload-artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts) action to save this directory. Something like:
```
      - name: Collect build results JSON
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: ${env.RUNNER_TEMP}/.build-results
```

That should help work out why the action is failing to parse these files in the post-action step.
