### ISSUE TITLE
Node warnings shown

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-build-action#474]
I get the following warning:

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/231070/196844559-9a0caf1f-ddbb-4b2a-9cc3-f39f2a327380.png">

The workflow file is very simple:
```
name: "Build"
on: [push, workflow_dispatch]

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Check out project
         uses: actions/checkout@v2
       - name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
           java-version: '11'
           distribution: 'adopt'
       - name: Build apps
         uses: gradle/gradle-build-action@v2
         with:
           arguments: build
```
