### ISSUE TITLE
Cache will not be saved: not restored in main action step.

### ISSUE THREAD

**Issue by leinardi** [gradle/gradle-build-action#479]
I have a non trivial workflow with several jobs running in parallel. Most of the jobs run on the slow GitHub Actions runner, but I also have a fast self hosted runner that can run one job at the time.

My idea was to build the gradle project on the fast runner and then share the cache with the other jobs, getting executed on a slow runner.

The problem is that the build job doesn't seem to save the cache:
```
Post job cleanup.
In final post-action step, saving state and writing summary
Cache will not be saved: not restored in main action step.
Writing job summary
```

This action is running on a PR and I'm aware that, by default, the cache is saved only when the action runs on the main branch, but I have manually set the `cache-read-only` to `false`, which is confirmed to be set correctly:
```
Run gradle/gradle-build-action@v2
  with:
    cache-read-only: false
    arguments: assembleDebug assembleDebugAndroidTest -PsaveBuildLogToFile=true
    cache-disabled: false
    cache-write-only: false
    gradle-home-cache-includes: caches
  notifications
  
    generate-job-summary: true
    gradle-home-cache-strict-match: false
    workflow-job-context: null
    gradle-home-cache-cleanup: false
```

This is the workflow:
```yml
name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  checks:
    name: Checking manifest and deps
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual task
      - name: Check merged manifests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: copyMergedManifests

      - uses: UnicornGlobal/has-changes-action@ea00e6f831a9e785271645729fa251907b314707
        id: merged_manifests

      - name: Check if there are changes
        if: steps.merged_manifests.outputs.changed == 1
        run: |
          echo '::error::Uncommitted changes to the merged manifests!'
          git diff
          exit 1

      - name: Check compile dependencies report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: generateRuntimeDependenciesReport

      - uses: UnicornGlobal/has-changes-action@ea00e6f831a9e785271645729fa251907b314707
        id: compile_dependencies_report

      - name: Check if there are changes
        if: steps.compile_dependencies_report.outputs.changed == 1
        run: |
          echo '::error::Uncommitted changes to the compile dependencies report!'
          exit 1

  build-debug:
    name: Build debug
    runs-on: android-runner-test
    timeout-minutes: 20
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual tasks
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: assembleDebug assembleDebugAndroidTest -PsaveBuildLogToFile=true

      - name: Archiving violations report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: violations-build-debug
          path: ./**/build/logs/buildlog*.txt

  build-release:
    name: Build release
    runs-on: ubuntu-latest
    needs: [build-debug]
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      - name: Decrypt secrets
        run: ./release/decrypt-secrets.sh
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      ## Actual task
      - name: Build
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_RELEASE_KEYSTORE_PWD: ${{ secrets.RELEASE_KEYSTORE_PWD }}
        with:
          arguments: bundleRelease analyzeReleaseBundle

      - name: Clean secrets
        if: always()
        run: ./release/clean-secrets.sh

      - name: Upload Ruler report
        uses: actions/upload-artifact@v3
        with:
          name: ruler
          path: app/build/reports/ruler

  detekt:
    name: Detekt
    runs-on: android-runner-test
    needs: [build-debug]
    timeout-minutes: 40
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual tasks
      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektDebug detektTest

      - name: Archiving violations report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: violations-detekt
          path: ./**/reports/detekt/*.xml

  spotless:
    name: Spotless
    runs-on: ubuntu-latest
    needs: [build-debug]
    timeout-minutes: 40
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual tasks
      - name: Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck

  android-lint:
    name: Android Lint
    runs-on: ubuntu-latest
    needs: [build-debug]
    timeout-minutes: 40
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual tasks
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint

      - name: Upload Lint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-lint-html-report
          path: ./**/build/reports/lint-results-*.html

      - name: Archiving violations report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: violations-android-lint
          path: ./**/reports/lint-results*.xml

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [build-debug]
    timeout-minutes: 40
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      ## Actual tasks
      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest

      - name: Archiving violations report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: violations-unit-tests
          path: ./**/build/test-results/test*/*.xml

  espresso-tests:
    name: Espresso tests (Sauce Labs)

    runs-on: ubuntu-latest
    needs: [build-debug]
    timeout-minutes: 45

    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      - name: Assemble App and Android tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug assembleDebugAndroidTest

      ## Actual task
      - name: Run Android tests
        uses: saucelabs/saucectl-run-action@v1
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          testing-environment: ''

      - name: Archiving violations report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: violations-espresso-tests
          path: ./**/build/sauce/saucectl-report.xml

  publishing-violation:
    name: Publishing violations to PR
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build-debug, detekt, android-lint, unit-tests, espresso-tests]
    timeout-minutes: 40
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11.0.14

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      ## This is needed by secrets-gradle-plugin
      - name: Create Local Properties File
        run: touch local.properties

      - name: Fetching build-debug result
        uses: actions/download-artifact@v3
        with:
          name: violations-build-debug

      - name: Fetching detekt result
        uses: actions/download-artifact@v3
        with:
          name: violations-detekt

      - name: Fetching android-lint result
        uses: actions/download-artifact@v3
        with:
          name: violations-android-lint

      - name: Fetching unit-tests result
        uses: actions/download-artifact@v3
        with:
          name: violations-unit-tests

      - name: Fetching espresso-tests result
        uses: actions/download-artifact@v3
        with:
          name: violations-espresso-tests

      ## Actual tasks
      - name: Publishing violation comments to PR
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: violationCommentsToGitHub -DGITHUB_PULLREQUESTID=${{ github.event.number }} -DGITHUB_OAUTH2TOKEN=${{ secrets.GITHUB_TOKEN }} --info
```

This image should help understand the workflow:
![image](https://user-images.githubusercontent.com/273338/197194884-9cbac49f-853e-4d94-8745-cb6d23d918da.png)

Again, the idea is to build and save the cache with the `build-debug` job to be able to reuse it in the following jobs on the same action but, when the `build-debug` job is over,  I get this message: `Cache will not be saved: not restored in main action step.`.

I'm not even sure what this "main action step" is (I tried to google but without any success).

Am I doing missing something regarding how the cache works?
