### ISSUE TITLE
Publish image to Github Container Registry

### ISSUE THREAD

**Issue by patsevanton** [gradle/gradle-build-action#50]
Hello! Thanks for gradle-command-action!

I have code to publish image to dockerhub:
```
      - name: Publish to DockerHub
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s jib
        env:
          GRADLE_OPTS: >
            -Djib.to.auth.username=${{ secrets.USERNAME }}
            -Djib.to.auth.password=${{ secrets.PASSWORD }}
```
How Publish image to Github Container Registry ?
Thanks!
