### ISSUE TITLE
Auto detect JVM toolchains in standard locations on GitHub runners

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#561]
The issue on the Gradle repo: https://github.com/gradle/gradle/issues/14903

Current workaround:

```yml
      - name: Create Gradle files
        run: |
          cd ~
          mkdir -p .gradle/ && touch .gradle/gradle.properties

      - name: Set up Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle Java installations paths
        run: |
          cd ~/.gradle
          echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
```
