### ISSUE TITLE
The latest version of gradle 8.0 is not supported

### ISSUE THREAD

**Issue by livk-cloud** [gradle/gradle-build-action#596]
![image](https://user-images.githubusercontent.com/50291874/218625413-034ba79e-dc0c-461f-b28f-5cfe103f9b0d.png)

```yaml
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: cleanAll build -D exclude=true
          gradle-version: 8.0
```
