### ISSUE TITLE
How can I execute bash scripts?

### ISSUE THREAD

**Issue by nuhkoca** [gradle/gradle-build-action#635]
Hello,

We usually have some complex logics. Is it possible to execute a bash script in `arguments`?

```yml
- name: Setup Gradle
  uses: gradle/gradle-build-action@v2
  with:
    gradle-version: current
    gradle-home-cache-cleanup: true

- name: Ktlint
  uses: gradle/gradle-build-action@v2
  with:
    arguments: bash ci/ktlint.sh <--- ?
```

throws

```
* What went wrong:
Task 'bash' not found in root project 'xxx' and its subprojects.
```

**Comment by bigdaz** [comment]
You shouldn't be referencing the `gradle-build-action` in the second step. Once the "Setup Gradle" step is complete, all subsequent Gradle invocations will benefit from this setup.

So something like this should work: 
```
- name: Setup Gradle
  uses: gradle/gradle-build-action@v2
  with:
    gradle-version: current
    gradle-home-cache-cleanup: true

- name: Ktlint
  run: bash ci/ktlint.sh // Any invocation of "gradle" will benefit from the prior setup.
```

[See here](https://github.com/gradle/gradle-build-action#use-the-action-to-setup-gradle) for an example and explanation.
