### ISSUE TITLE
Feature request: Allow to switch cache provider

### ISSUE THREAD

**Issue by gmazzo** [gradle/gradle-build-action#752]
Hi there, we were recently exploring this action and noted it's coupled with GitHub's Cache API. Could you consider opening to work with another cache provider instead?

We are initially targeting S3, like this other  [`actions/cache` drop-in  replacement](https://github.com/marketplace/actions/s3-cache-for-github-actions). But having the ability to specify the handler will be ideal. On top of my mind, I was thinking something like:
```yaml
cache-provider: github # default
cache-provider: s3://xxx
cache-provider: https://xxx.yyy/zzz?${key}=${value}
```
