### ISSUE TITLE
Gradle option `--parallel` has no affect when running on GitHub

### ISSUE THREAD

**Issue by tglaeser** [gradle/gradle-build-action#773]
Using `gradle/gradle-build-action` to run Gradle with switch `--parallel` seems to have no affect compared to without it. E.g.
```
name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
    - uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build --parallel
```
will result in the same performance as without `--parallel`.

Is this as expected? Anything that can be done about that?

**Comment by bigdaz** [comment]
There's nothing in the `gradle-build-action` that would be directly impacting this.
If this is indeed the case, it's more likely due to the number of CPUs being detected on the runner, since this will impact the default parallelism of a Gradle build.

A few things you could try:
1. Compare the performace running with and without `--parallel`, _without using the gradle-build-action_
2. Try setting `--max-workers=X` since this will override the default, which is based on the number of CPUs detected on the machine.
3. Generate (and share) a [Gradle Build Scan](https://scans.gradle.com/) so you can visualize the parallelism of your build.

**Comment by tglaeser** [comment]
Thanks. I actually did (1) and (2), but on my local machine only. Now here the numbers from the CI machine:
```
gradle clean dependencyReport build --parallel --max-workers=8
```
^ `3m 58s`
```
gradle clean dependencyReport build
```
^ `5m 31s`
```
jobs:
  integration:
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean dependencyReport build --parallel --max-workers=8
```
^ `5m 48s`
```
jobs:
  integration:
    steps:
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean dependencyReport build
```
^ `8m 44s`

Generally, it seems that execution via the GitHub Gradle action adds quite some overhead compared to the direct execution from the command line.
