### ISSUE TITLE
Caching default options are different from README in the main branch

### ISSUE THREAD

**Issue by hojongs** [gradle/gradle-build-action#79]
### Overview

main README
> Each of these are enabled by default. To save caching space, you can disable any of them as follows:

v1.5.1 README
> Only the first one, caching downloaded distributions, is enabled by default. Future versions of this action will enable all caching by default.

### Description

I've tried to use this action. before I use it, I read the README and caching part.
The version of README was the main branch. It said caching for distribution, dependencies, configuration are all enabled by default.

But, when I used `gradle-build-action@v1`, It only enabled distribution caching, others are disabled. (I realized it after spending a lot of time)

I checked the README of v1.5.1(latest version), the default option was different from the document I've seen.

I guess most users will read README in the main branch, not the latest tagging branch.
It'll be better to sync README in the main branch with the latest version's options.

### Reference

[main branch](https://github.com/gradle/gradle-build-action#caching)
[v1.5.1](https://github.com/gradle/gradle-build-action/tree/v1.5.1#caching)

**Comment by hojongs** [comment]
Even more, the option keys are different.

main

```yml
distributions-cache-enabled: true
gradle-user-home-cache-enabled: true
project-dot-gradle-cache-enabled: true
```

v1.5.1

```yml
distributions-cache-enabled: true
dependencies-cache-enabled: true
configuration-cache-enabled: true
```

I realized it after seeing the warning message.

```
Warning: Unexpected input(s) 'gradle-user-home-cache-enabled', 'project-dot-gradle-cache-enabled', valid inputs are ['wrapper-directory', 'gradle-executable', 'gradle-version', 'build-root-directory', 'arguments', 'distributions-cache-enabled', 'wrapper-cache-enabled', 'dependencies-cache-enabled', 'dependencies-cache-key', 'dependencies-cache-exact', 'configuration-cache-enabled', 'configuration-cache-key', 'configuration-cache-exact', 'cache-read-only']
```
