### ISSUE TITLE
Add support to output command output to GITHUB_STEP_SUMMARY

### ISSUE THREAD

**Issue by peterdietz** [gradle/gradle-build-action#833]
Other build pipelines allow me to output the text output of a command to the GitHub Step Summary, such that the build will display some additional information. And not just hidden inside of the logs of a step. 

Would you consider adding a feature for this? Maybe add a parameter `write-to-step-summary: true`?

In bash, I'll do something like:
```
      - name: Report Something
        run: cat output.md >> $GITHUB_STEP_SUMMARY
        shell: bash
```

But in gradle-build-action, I would like something like this:
```
      - name: Print Application Build Version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: printVersion
          cache-read-only: false
          gradle-version: ${{ env.GRADLE_VERSION }}
          write-to-step-summary: true
```

As I integrate more of my jobs with Build/Publishing artifacts, its very helpful to sanity check which version of the app wrote an artifact. Thank you!

**Comment by bigdaz** [comment]
In order to achieve this, you can separate the `gradle-build-action` step from the actual Gradle execution, like so: 
```
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Print Application Build Version
        run: gradle printVersion >> $GITHUB_STEP_SUMMARY
```

In fact, I would recommend that you always use `gradle-build-action` as a "Setup Gradle" step. This will likely become a more formal recommendation in the future.

Because of this simple workaround, I'm reluctant to add a new feature for this purpose.
