### ISSUE TITLE
How to handle dependency submission in multi-step build workflow?

### ISSUE THREAD

**Issue by big-andy-coates** [gradle/gradle-build-action#843]
Hi,

I'm playing around with the new dependency submission feature (great to see this!) and I have a question about intended use / patterns when there are multiple calls to Gradle in the build.

For example:

```yaml
name: CI
on: <stuff>
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit
    - name: Run a build, generating the dependency graph snapshot which will be submitted
      run: ./gradlew build
    - name: Publish
      if: <stuff>
      run: ./gradlew publish
```

In the above workflow Gradle will build two dependency reports, one for each of the ./gradlew calls.

Generally, this second report isn't intentional!

The situation is also confusing for users If they want to filter by configuration and/or project. If they naively just add the necessary `DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS` and/or `DEPENDENCY_GRAPH_INCLUDE_PROJECTS` vars to the first `build` step, then only the first report is filtered. The second report is unfiltered, so all dependencies are submitted to GitHub.  To correctly filter, users need to _remember_ to set env vars _on all Gradle steps_ and _remember_ to keep them in sync going forward.

*Question:* what is the intended pattern to limit the build to generate only a single dependency report?  

Maybe a second `gradle/gradle-build-action` step after the first `build` step?  But then would this not require users to remember to keep the settings of these two steps insync?

**Comment by bigdaz** [comment]
Speaking with the GitHub team, they would rather that users default to publishing _all_ of their dependencies, and are planning to add tools to make it easier to manage these.

But I understand that for now you are trying to publish a subset of dependencies to avoid getting vulnerability reports for dependencies that you consider unimportant.

One option you have is to use a separate workflow to generate the dependency graph, completely separate from your regular CI workflow. This would be similar to the way CodeQL works. This workflow would do as little computation as possible while resolving the necessary dependencies. For example: `gradle :my-app:dependencies --configuration RuntimeClasspath`.

To address your specific scenario, you can disable dependency graph generation for the "Publish" step with:
```
    - name: Publish
      if: <stuff>
      run: ./gradlew publish
      env:
         # This is set to 'true' by the 'gradle-build-action'
         GITHUB_DEPENDENCY_GRAPH_ENABLED: false
```

Under the hood this works because dependency graph plugin is applied via [this init script](https://github.com/gradle/gradle-build-action/blob/main/src/resources/init-scripts/github-dependency-graph.init.gradle).

PS Thanks for the questions. I'm currently working on improving the documentation around dependency-graph support, and this is prompting me to write the content!
