### ISSUE TITLE
Setup Java Environment functionality with a parameter

### ISSUE THREAD

**Issue by mustafaozhan** [gradle/gradle-build-action#852]
I was wondering if we can put java setup into `gradle-build-action` with an extra parameter. I don't know if it is possible according to GitHub action rules and limitations.

So currently, people with Java/Kotlin & Android world has to do this:
```
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Assemble
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: assemble
```
But If we could add a parameter to `gradle-build-action`  ie `java-version: X`  and when this is applied `gradle-build-action` can apply the `actions/setup-java@v3` under the hood.
```
      - name: Assemble
        uses: gradle/gradle-build-action@v2.7.0
        with:
 		  java-version: 17
          arguments: assemble
```

This will allow us having less lines of codes in GitHub Action yml files.
