### ISSUE TITLE
Support GitHub dependencies review action/api

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle-build-action#879]
Currently, the dependency submission is called in the Post step, not directly after the execution of Gradle. This is incompatible with the https://github.com/actions/dependency-review-action, which validates the submitted dependencies (from a PR) and will fail your build, eg if you submit vulnerabilities in the PR. The review action needs to be run after Gradle and after the submission of dependencies.

**Comment by hfhbd** [comment]
Hm, don't know if this is a GitHub issue, but the workaround to run the review action in another job didn't work:
```yml
  reviewDependencies:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/dependency-review-action@v3
        with:
          retry-on-snapshot-warnings: true
```
https://github.com/hfhbd/ComposeTodo/blob/603a57e66752a8f2f7602a32f2fd657053a77437/.github/workflows/CI.yml
