### ISSUE TITLE
Support multi-line arguments

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#88]
Supplying the entire argument list on a single line can be cumbersome and make the workflow file difficult to read. A relatively simple solution would be to allow `arguments` to be supplied as a multi-line input. So instead of:
```
 - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info -PsomeService.prod.apiKey=${{ secrets.SOME_SERVICE_API_KEY }} -PsomeService.prod.secret=${{ secrets.SOME_SERVICE_API_SECRET }} -PsomeService.prod.projectId=${{ secrets.SOME_SERVICE_PROJECT_ID }}
```

one could use:
```
- name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
             build --info 
             -PsomeService.prod.apiKey=${{ secrets.SOME_SERVICE_API_KEY }} 
             -PsomeService.prod.secret=${{ secrets.SOME_SERVICE_API_SECRET }} 
             -PsomeService.prod.projectId=${{ secrets.SOME_SERVICE_PROJECT_ID }}
```

I think this option is preferable to a [structured input parameter for properties](https://github.com/gradle/gradle-build-action/issues/18) since it keeps the action API simpler and is likely easier for new users to learn and understand.

Thanks @vlsi for the inspiration: https://github.com/gradle/gradle-build-action/issues/18#issuecomment-670580368.
