### ISSUE TITLE
Running different tasks results into different dependency graphs

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle-build-action#880]
I run the following Gradle tasks: `build` and `detekt`, so I get 3 dependency graphs (`build`, `detekt`, `cleanup`). These files differs: 
- They have different artifacts, the 2nd run (`detekt`) misses many artifacts.
- Some artifacts are marked as `direct` in the first graph, but `indirect` in the second run.
- The `cleanup` graph is empty.

AFAIK GitHub uses the latest one (same correlator, higher timestamp) as final results, resulting in less dependencies.

Results: https://github.com/hfhbd/ComposeTodo/suites/15996628865/artifacts/913210709

CI run: https://github.com/hfhbd/ComposeTodo/actions/runs/6133473569/job/16645352703

CI config:
```yml
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      security-events: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
          gradle-home-cache-cleanup: true
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-kotlin-1.9.10
          path:
            ~/.konan
      - name: Build with Gradle
        run: ./gradlew build

      - name: Detekt
        run: ./gradlew detekt
        if: always()
```
