### ISSUE TITLE
Dedicated workflow for dependency graph generation generates all possible configurations

### ISSUE THREAD

**Issue by wzieba** [gradle/gradle-build-action#976]
### Issue

When using a dedicated workflow for dependency graph generation as described [here](https://github.com/gradle/gradle-build-action?tab=readme-ov-file#use-a-dedicated-workflow-for-dependency-graph-generation), the generated dependency graph contains dependencies from all the configurations, instead of only the requested one.

### Reproduction

I've prepared MRE here: https://github.com/wzieba/GradleBuildActionTest

The `detekt` plugin is just an example of some build plugin.

Having a Gradle project 

```kotlin
// build.gradle.kts
plugins {
    application
    id("io.gitlab.arturbosch.detekt")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("javax.inject:javax.inject:1")
}
```

```kotlin
// settings.gradle.kts
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    plugins {
        id 'io.gitlab.arturbosch.detekt' version '1.19.0'
    }
}
```

In such project, the result of `dependencies --configuration runtimeClasspath` is 
```shell
❯ ./gradlew dependencies --configuration runtimeClasspath

> Task :dependencies

------------------------------------------------------------
Root project 'GradleBuildActionTest'
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
\--- javax.inject:javax.inject:1
```

Then, with GitHub Action
```yaml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate
      - name: Extract the 'runtimeClasspath' dependencies
        run: ./gradlew dependencies --configuration runtimeClasspath
```

#### Expected result

I expect that the generated `dependency-graph` file will contain **only `javax.inject:javax.inject:1` dependency** (and its transitive dependencies if any).

#### Current result

The generated `dependency-graph` ([link](https://github.com/wzieba/GradleBuildActionTest/actions/runs/7060274330)) contains all project dependencies, including `Detekt` and `Kotlin` (transitive dependency of `Detekt`)
