### ISSUE TITLE
Automatically upload build reports as workflow artifacts

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle-build-action#98]
It's not unusual for workflows to contain a step following `gradle-build-action` to upload build reports as artifacts, like:
```
      - name: Store reports
        uses: actions/upload-artifact@v2
        with:
          name: linux-reports
          path: build/reports/
```

It would be nice to do this automatically (via opt-in parameter), with a sensible default path for build reports.
